#!/usr/bin/env python

from provision import openshift_setup
from provision import persistent_vol
from argparse import ArgumentParser, RawTextHelpFormatter


if __name__ == '__main__':
    parser = ArgumentParser(prog='openshift_provision',
            description='CLI to provision OpenShift for different usecase',
            formatter_class=RawTextHelpFormatter)
    parser.add_argument('-s', '--setup', help="OpenShift basic Setup")
    parser.add_argument('-a', '--addon', nargs="+",
            help="""Enable an addon (persistent volume), cockpit, metrix, logging
    $ openshift_provision -a pv <number_of_pv> <size_of_pv> default(3, 1Gb)
    $ openshift_provision -a metrix
    $ openshift_provision -a cockpit
    $ openshift_provision -a logging""")
    args = parser.parse_args()
    if args.setup:
        openshift_setup()
    else:
        addon_name = args.addon[0]
        if addon_name == 'pv':
            number_of_pv = args.addon[1] if args.addon[1:] else 3
            size_of_pv = args.addon[2] if args.addon[2:] else 1
            persistent_vol.persistent_vol_setup(int(number_of_pv),
                                                int(size_of_pv))

